### ISSUE TITLE
ESP8266 halting

### ISSUE THREAD

**Issue by segallis** [vshymanskyy/blynk-library-python#51] opened 2021-02-17 21:18 UTC
My ESP8266 intermittently drops out of the main loop after minutes (20 to 40 usually).  I tried heartbeat set to 30 and 10.  I am running my own local server.  The app still sees the blynk server, so I believe the issue is on the ESP8266.

Also, If I kill the blynk local server (to simulate a server reboot or power failure, which will definitely happen), the ESP8266 halts with an error.  Is there a way to keep the ESP8266 code running so things get back to normal when the server restarts?

**Comment by vshymanskyy** [comment] 2021-06-28 23:22
Duplicate of #36

**Closed by vshymanskyy** 2021-06-28 23:22 UTC
